name: Update Last Modified Date

on:
  push:
    branches:
      - main

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update last modified date in Markdown files
        run: |
          for file in $(find . -name "*.md"); do
            LAST_MODIFIED=$(git log -1 --format="%ad" --date=format:"%d %B %Y" "$file")
            if grep -q "^last_modified_at:" "$file"; then
              sed -i "s/^last_modified_at:.*/last_modified_at: $LAST_MODIFIED/" "$file"
            else
              echo -e "---\nlast_modified_at: $LAST_MODIFIED\n$(cat "$file")" > "$file"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Aggiornata ultima data di modifica"
          git push
